name: "release-tag"

on:
  push:
    branches:
      - master
    tags:
      - 2.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build
        run: dotnet build -c Release
      - name: Tests
        run: dotnet test -c Release --no-build
      - name: Pack artifacts
        run: dotnet pack src -c Release  --no-build -o artifacts/
      - name: Collect artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: artifacts/
